//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ognas.Lib.Shoguns {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ShogunBasicInfoResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShogunBasicInfoResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ognas.Lib.Shoguns.ShogunBasicInfoResource", typeof(ShogunBasicInfoResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 0x01|曹操|0x01|0x01|4 的本地化字符串。
        /// </summary>
        internal static string CaoCao {
            get {
                return ResourceManager.GetString("CaoCao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0x09|曹仁|0x01|0x01|4 的本地化字符串。
        /// </summary>
        internal static string CaoRen {
            get {
                return ResourceManager.GetString("CaoRen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0x44|大乔|0x02|0x03|3 的本地化字符串。
        /// </summary>
        internal static string DaQiao {
            get {
                return ResourceManager.GetString("DaQiao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0x62|吕布|0x01|0x04|3 的本地化字符串。
        /// </summary>
        internal static string DiaoChan {
            get {
                return ResourceManager.GetString("DiaoChan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0x47|甘宁|0x01|0x03|4 的本地化字符串。
        /// </summary>
        internal static string GanNing {
            get {
                return ResourceManager.GetString("GanNing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0x26|关羽|0x01|0x02|4 的本地化字符串。
        /// </summary>
        internal static string GuanYu {
            get {
                return ResourceManager.GetString("GuanYu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0x06|郭嘉|0x01|0x01|3 的本地化字符串。
        /// </summary>
        internal static string GuoJia {
            get {
                return ResourceManager.GetString("GuoJia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0x45|黄盖|0x01|0x03|4 的本地化字符串。
        /// </summary>
        internal static string HuangGai {
            get {
                return ResourceManager.GetString("HuangGai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0x23|黄月英|0x02|0x02|3 的本地化字符串。
        /// </summary>
        internal static string HuangYueYing {
            get {
                return ResourceManager.GetString("HuangYueYing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0x28|黄忠|0x01|0x02|4 的本地化字符串。
        /// </summary>
        internal static string HuangZhong {
            get {
                return ResourceManager.GetString("HuangZhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0x63|华佗|0x01|0x04|3 的本地化字符串。
        /// </summary>
        internal static string HuaTuo {
            get {
                return ResourceManager.GetString("HuaTuo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0x21|刘备|0x01|0x02|4 的本地化字符串。
        /// </summary>
        internal static string LiuBei {
            get {
                return ResourceManager.GetString("LiuBei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0x42|陆逊|0x01|0x03|3 的本地化字符串。
        /// </summary>
        internal static string LuXun {
            get {
                return ResourceManager.GetString("LuXun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0x62|吕布|0x01|0x04|4 的本地化字符串。
        /// </summary>
        internal static string LvBu {
            get {
                return ResourceManager.GetString("LvBu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0x46|吕蒙|0x01|0x03|4 的本地化字符串。
        /// </summary>
        internal static string LvMeng {
            get {
                return ResourceManager.GetString("LvMeng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0x22|马超|0x01|0x02|4 的本地化字符串。
        /// </summary>
        internal static string MaChao {
            get {
                return ResourceManager.GetString("MaChao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0x07|司马懿|0x01|0x01|3 的本地化字符串。
        /// </summary>
        internal static string SiMaYi {
            get {
                return ResourceManager.GetString("SiMaYi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0x41|孙权|0x01|0x03|4 的本地化字符串。
        /// </summary>
        internal static string SunQuan {
            get {
                return ResourceManager.GetString("SunQuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0x48|孙尚香|0x02|0x03|3 的本地化字符串。
        /// </summary>
        internal static string SunShangXiang {
            get {
                return ResourceManager.GetString("SunShangXiang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0x29|魏延|0x01|0x02|4 的本地化字符串。
        /// </summary>
        internal static string WeiYan {
            get {
                return ResourceManager.GetString("WeiYan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0x03|夏侯惇|0x01|0x01|4 的本地化字符串。
        /// </summary>
        internal static string XiaHouDun {
            get {
                return ResourceManager.GetString("XiaHouDun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0x08|夏侯渊|0x01|0x01|4 的本地化字符串。
        /// </summary>
        internal static string XiaHouYuan {
            get {
                return ResourceManager.GetString("XiaHouYuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0x49|小乔|0x02|0x03|3 的本地化字符串。
        /// </summary>
        internal static string XiaoQiao {
            get {
                return ResourceManager.GetString("XiaoQiao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0x04|许褚|0x01|0x01|4 的本地化字符串。
        /// </summary>
        internal static string XuChu {
            get {
                return ResourceManager.GetString("XuChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0x65|于吉|0x01|0x04|3 的本地化字符串。
        /// </summary>
        internal static string YuJi {
            get {
                return ResourceManager.GetString("YuJi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0x25|张飞|0x01|0x02|4 的本地化字符串。
        /// </summary>
        internal static string ZhangFei {
            get {
                return ResourceManager.GetString("ZhangFei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0x64|张角|0x01|0x04|3 的本地化字符串。
        /// </summary>
        internal static string ZhangJiao {
            get {
                return ResourceManager.GetString("ZhangJiao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0x05|张辽|0x01|0x01|4 的本地化字符串。
        /// </summary>
        internal static string ZhangLiao {
            get {
                return ResourceManager.GetString("ZhangLiao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0x24|赵云|0x01|0x02|4 的本地化字符串。
        /// </summary>
        internal static string ZhaoYun {
            get {
                return ResourceManager.GetString("ZhaoYun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0x02|甄姬|0x02|0x01|3 的本地化字符串。
        /// </summary>
        internal static string ZhenJi {
            get {
                return ResourceManager.GetString("ZhenJi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0x61|周泰|0x02|0x03|4 的本地化字符串。
        /// </summary>
        internal static string ZhouTai {
            get {
                return ResourceManager.GetString("ZhouTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0x43|周瑜|0x01|0x03|3 的本地化字符串。
        /// </summary>
        internal static string ZhouYu {
            get {
                return ResourceManager.GetString("ZhouYu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0x27|诸葛亮|0x01|0x02|3 的本地化字符串。
        /// </summary>
        internal static string ZhuGeLiang {
            get {
                return ResourceManager.GetString("ZhuGeLiang", resourceCulture);
            }
        }
    }
}
