//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ognas.Resource
{
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Images_Skill
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Images_Skill()
        {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ognas.Resource.Images.Skill", typeof(Images_Skill).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        public static System.Drawing.Bitmap Bgz1
        {
            get
            {
                object obj = ResourceManager.GetObject("Bgz1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Blcd1
        {
            get
            {
                object obj = ResourceManager.GetObject("Blcd1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Bysz1
        {
            get
            {
                object obj = ResourceManager.GetObject("Bysz1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Ct1
        {
            get
            {
                object obj = ResourceManager.GetObject("Ct1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Cxsgj1
        {
            get
            {
                object obj = ResourceManager.GetObject("Cxsgj1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Dl1
        {
            get
            {
                object obj = ResourceManager.GetObject("Dl1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Dw1
        {
            get
            {
                object obj = ResourceManager.GetObject("Dw1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Fthj1
        {
            get
            {
                object obj = ResourceManager.GetObject("Fthj1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Gdd1
        {
            get
            {
                object obj = ResourceManager.GetObject("Gdd1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Ghcq1
        {
            get
            {
                object obj = ResourceManager.GetObject("Ghcq1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Gsf1
        {
            get
            {
                object obj = ResourceManager.GetObject("Gsf1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Hbj1
        {
            get
            {
                object obj = ResourceManager.GetObject("Hbj1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Hg1
        {
            get
            {
                object obj = ResourceManager.GetObject("Hg1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Jd1
        {
            get
            {
                object obj = ResourceManager.GetObject("Jd1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Jdsr1
        {
            get
            {
                object obj = ResourceManager.GetObject("Jdsr1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Jiu1
        {
            get
            {
                object obj = ResourceManager.GetObject("Jiu1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Jy1
        {
            get
            {
                object obj = ResourceManager.GetObject("Jy1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Lbss1
        {
            get
            {
                object obj = ResourceManager.GetObject("Lbss1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Nmrq1
        {
            get
            {
                object obj = ResourceManager.GetObject("Nmrq1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Qhj1
        {
            get
            {
                object obj = ResourceManager.GetObject("Qhj1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Qlg1
        {
            get
            {
                object obj = ResourceManager.GetObject("Qlg1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Qlyyd1
        {
            get
            {
                object obj = ResourceManager.GetObject("Qlyyd1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Rwd1
        {
            get
            {
                object obj = ResourceManager.GetObject("Rwd1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Sd1
        {
            get
            {
                object obj = ResourceManager.GetObject("Sd1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Sha1
        {
            get
            {
                object obj = ResourceManager.GetObject("Sha1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Sha2
        {
            get
            {
                object obj = ResourceManager.GetObject("Sha2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Sha3
        {
            get
            {
                object obj = ResourceManager.GetObject("Sha3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Shan1
        {
            get
            {
                object obj = ResourceManager.GetObject("Shan1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Ssqy1
        {
            get
            {
                object obj = ResourceManager.GetObject("Ssqy1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Tao1
        {
            get
            {
                object obj = ResourceManager.GetObject("Tao1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Tj1
        {
            get
            {
                object obj = ResourceManager.GetObject("Tj1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Tslh1
        {
            get
            {
                object obj = ResourceManager.GetObject("Tslh1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Tyjy1
        {
            get
            {
                object obj = ResourceManager.GetObject("Tyjy1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Wgfd1
        {
            get
            {
                object obj = ResourceManager.GetObject("Wgfd1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Wjqf1
        {
            get
            {
                object obj = ResourceManager.GetObject("Wjqf1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Wxkj1
        {
            get
            {
                object obj = ResourceManager.GetObject("Wxkj1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Wzsy1
        {
            get
            {
                object obj = ResourceManager.GetObject("Wzsy1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Zbsm1
        {
            get
            {
                object obj = ResourceManager.GetObject("Zbsm1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Zgln1
        {
            get
            {
                object obj = ResourceManager.GetObject("Zgln1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Zhfd1
        {
            get
            {
                object obj = ResourceManager.GetObject("Zhfd1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Zqys1
        {
            get
            {
                object obj = ResourceManager.GetObject("Zqys1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        public static System.Drawing.Bitmap Zs1
        {
            get
            {
                object obj = ResourceManager.GetObject("Zs1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
