//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ognas.Resource
{
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Skills
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Skills()
        {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ognas.Resource.Skills", typeof(Skills).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 0x04|闪电|0x01|0x01|Shan1 的本地化字符串。
        /// </summary>
        public static string _60
        {
            get
            {
                return ResourceManager.GetString("60", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x1F|八卦阵|0x01|0x02|Bgz1 的本地化字符串。
        /// </summary>
        public static string _61
        {
            get
            {
                return ResourceManager.GetString("61", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x0F|过河拆桥|0x01|0x03|Ghcq1 的本地化字符串。
        /// </summary>
        public static string _62
        {
            get
            {
                return ResourceManager.GetString("62", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x0F|过河拆桥|0x01|0x04|Ghcq1 的本地化字符串。
        /// </summary>
        public static string _63
        {
            get
            {
                return ResourceManager.GetString("63", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x1B|青龙偃月刀|0x01|0x05|Qlyyd1 的本地化字符串。
        /// </summary>
        public static string _64
        {
            get
            {
                return ResourceManager.GetString("64", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x05|乐不思蜀|0x01|0x06|Lbss1 的本地化字符串。
        /// </summary>
        public static string _65
        {
            get
            {
                return ResourceManager.GetString("65", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x0C|南蛮入侵|0x01|0x07|Nmrq1 的本地化字符串。
        /// </summary>
        public static string _66
        {
            get
            {
                return ResourceManager.GetString("66", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x01|杀|0x01|0x08|Sha1 的本地化字符串。
        /// </summary>
        public static string _67
        {
            get
            {
                return ResourceManager.GetString("67", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x01|杀|0x01|0x09|Sha1 的本地化字符串。
        /// </summary>
        public static string _68
        {
            get
            {
                return ResourceManager.GetString("68", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x01|杀|0x01|0x0A|Sha1 的本地化字符串。
        /// </summary>
        public static string _69
        {
            get
            {
                return ResourceManager.GetString("69", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x06|无懈可击|0x01|0x0B|Wxkj1 的本地化字符串。
        /// </summary>
        public static string _6A
        {
            get
            {
                return ResourceManager.GetString("6A", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x1C|丈八蛇矛|0x01|0x0C|Zbsm1 的本地化字符串。
        /// </summary>
        public static string _6B
        {
            get
            {
                return ResourceManager.GetString("6B", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x15|大宛|0x01|0x0D|Dw1 的本地化字符串。
        /// </summary>
        public static string _6C
        {
            get
            {
                return ResourceManager.GetString("6C", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x0B|桃园结义|0x02|0x01|Tyjy1 的本地化字符串。
        /// </summary>
        public static string _6D
        {
            get
            {
                return ResourceManager.GetString("6D", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x02|闪|0x02|0x02|Shan1 的本地化字符串。
        /// </summary>
        public static string _6E
        {
            get
            {
                return ResourceManager.GetString("6E", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x03|桃|0x02|0x03|Tao1 的本地化字符串。
        /// </summary>
        public static string _6F
        {
            get
            {
                return ResourceManager.GetString("6F", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x03|桃|0x02|0x04|Tao1 的本地化字符串。
        /// </summary>
        public static string _70
        {
            get
            {
                return ResourceManager.GetString("70", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x1E|麒麟弓|0x02|0x05|Qlg1 的本地化字符串。
        /// </summary>
        public static string _71
        {
            get
            {
                return ResourceManager.GetString("71", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x03|桃|0x02|0x06|Tao1 的本地化字符串。
        /// </summary>
        public static string _72
        {
            get
            {
                return ResourceManager.GetString("72", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x03|桃|0x02|0x07|Tao1 的本地化字符串。
        /// </summary>
        public static string _73
        {
            get
            {
                return ResourceManager.GetString("73", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x03|桃|0x02|0x08|Tao1 的本地化字符串。
        /// </summary>
        public static string _74
        {
            get
            {
                return ResourceManager.GetString("74", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x03|桃|0x02|0x09|Tao1 的本地化字符串。
        /// </summary>
        public static string _75
        {
            get
            {
                return ResourceManager.GetString("75", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x01|杀|0x02|0x0A|Sha1 的本地化字符串。
        /// </summary>
        public static string _76
        {
            get
            {
                return ResourceManager.GetString("76", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x01|杀|0x02|0x0B|Sha1 的本地化字符串。
        /// </summary>
        public static string _77
        {
            get
            {
                return ResourceManager.GetString("77", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x03|桃|0x02|0x0C|Tao1 的本地化字符串。
        /// </summary>
        public static string _78
        {
            get
            {
                return ResourceManager.GetString("78", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x10|爪黄飞电|0x02|0x0D|Zhfd1 的本地化字符串。
        /// </summary>
        public static string _79
        {
            get
            {
                return ResourceManager.GetString("79", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x16|诸葛连弩|0x03|0x01|Zgln1 的本地化字符串。
        /// </summary>
        public static string _7A
        {
            get
            {
                return ResourceManager.GetString("7A", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x1F|八卦阵|0x03|0x02|Bgz1 的本地化字符串。
        /// </summary>
        public static string _7B
        {
            get
            {
                return ResourceManager.GetString("7B", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x0F|过河拆桥|0x03|0x03|Ghcq1 的本地化字符串。
        /// </summary>
        public static string _7C
        {
            get
            {
                return ResourceManager.GetString("7C", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x0F|过河拆桥|0x03|0x04|Ghcq1 的本地化字符串。
        /// </summary>
        public static string _7D
        {
            get
            {
                return ResourceManager.GetString("7D", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x11|的卢|0x03|0x05|Dl1 的本地化字符串。
        /// </summary>
        public static string _7E
        {
            get
            {
                return ResourceManager.GetString("7E", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x05|乐不思蜀|0x03|0x06|Lbss1 的本地化字符串。
        /// </summary>
        public static string _7F
        {
            get
            {
                return ResourceManager.GetString("7F", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x0C|南蛮入侵|0x03|0x07|Nmrq1 的本地化字符串。
        /// </summary>
        public static string _80
        {
            get
            {
                return ResourceManager.GetString("80", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x01|杀|0x03|0x08|Sha1 的本地化字符串。
        /// </summary>
        public static string _81
        {
            get
            {
                return ResourceManager.GetString("81", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x01|杀|0x03|0x09|Sha1 的本地化字符串。
        /// </summary>
        public static string _82
        {
            get
            {
                return ResourceManager.GetString("82", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x01|杀|0x03|0x0A|Sha1 的本地化字符串。
        /// </summary>
        public static string _83
        {
            get
            {
                return ResourceManager.GetString("83", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x01|杀|0x03|0x0B|Sha1 的本地化字符串。
        /// </summary>
        public static string _84
        {
            get
            {
                return ResourceManager.GetString("84", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x07|借刀杀人|0x03|0x0C|Jdsr1 的本地化字符串。
        /// </summary>
        public static string _85
        {
            get
            {
                return ResourceManager.GetString("85", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x07|借刀杀人|0x03|0x0D|Jdsr1 的本地化字符串。
        /// </summary>
        public static string _86
        {
            get
            {
                return ResourceManager.GetString("86", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x16|诸葛连弩|0x04|0x01|Zgln1 的本地化字符串。
        /// </summary>
        public static string _87
        {
            get
            {
                return ResourceManager.GetString("87", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x02|闪|0x04|0x02|Shan1 的本地化字符串。
        /// </summary>
        public static string _88
        {
            get
            {
                return ResourceManager.GetString("88", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x02|闪|0x04|0x03|Shan1 的本地化字符串。
        /// </summary>
        public static string _89
        {
            get
            {
                return ResourceManager.GetString("89", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x02|闪|0x04|0x04|Shan1 的本地化字符串。
        /// </summary>
        public static string _8A
        {
            get
            {
                return ResourceManager.GetString("8A", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x02|闪|0x04|0x05|Shan1 的本地化字符串。
        /// </summary>
        public static string _8B
        {
            get
            {
                return ResourceManager.GetString("8B", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x02|闪|0x04|0x06|Shan1 的本地化字符串。
        /// </summary>
        public static string _8C
        {
            get
            {
                return ResourceManager.GetString("8C", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x02|闪|0x04|0x07|Shan1 的本地化字符串。
        /// </summary>
        public static string _8D
        {
            get
            {
                return ResourceManager.GetString("8D", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x02|闪|0x04|0x08|Shan1 的本地化字符串。
        /// </summary>
        public static string _8E
        {
            get
            {
                return ResourceManager.GetString("8E", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x02|闪|0x04|0x09|Shan1 的本地化字符串。
        /// </summary>
        public static string _8F
        {
            get
            {
                return ResourceManager.GetString("8F", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x02|闪|0x04|0x0A|Shan1 的本地化字符串。
        /// </summary>
        public static string _90
        {
            get
            {
                return ResourceManager.GetString("90", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x02|闪|0x04|0x0B|Shan1 的本地化字符串。
        /// </summary>
        public static string _91
        {
            get
            {
                return ResourceManager.GetString("91", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x03|桃|0x04|0x0C|Tao1 的本地化字符串。
        /// </summary>
        public static string _92
        {
            get
            {
                return ResourceManager.GetString("92", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x01|杀|0x04|0x0D|Sha1 的本地化字符串。
        /// </summary>
        public static string _93
        {
            get
            {
                return ResourceManager.GetString("93", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x0A|决斗|0x01|0x01|Jd1 的本地化字符串。
        /// </summary>
        public static string _94
        {
            get
            {
                return ResourceManager.GetString("94", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x19|决斗|0x01|0x02|Jd1 的本地化字符串。
        /// </summary>
        public static string _95
        {
            get
            {
                return ResourceManager.GetString("95", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x0E|顺手牵羊|0x01|0x03|Ssqy1 的本地化字符串。
        /// </summary>
        public static string _96
        {
            get
            {
                return ResourceManager.GetString("96", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x0E|顺手牵羊|0x01|0x04|Ssqy1 的本地化字符串。
        /// </summary>
        public static string _97
        {
            get
            {
                return ResourceManager.GetString("97", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x12|绝影|0x01|0x05|Jy1 的本地化字符串。
        /// </summary>
        public static string _98
        {
            get
            {
                return ResourceManager.GetString("98", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x18|青釭剑|0x01|0x06|Qhj1 的本地化字符串。
        /// </summary>
        public static string _99
        {
            get
            {
                return ResourceManager.GetString("99", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x01|杀|0x01|0x07|Sha1 的本地化字符串。
        /// </summary>
        public static string _9A
        {
            get
            {
                return ResourceManager.GetString("9A", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x01|杀|0x01|0x08|Sha1 的本地化字符串。
        /// </summary>
        public static string _9B
        {
            get
            {
                return ResourceManager.GetString("9B", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x01|杀|0x01|0x09|Sha1 的本地化字符串。
        /// </summary>
        public static string _9C
        {
            get
            {
                return ResourceManager.GetString("9C", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x01|杀|0x01|0x0A|Sha1 的本地化字符串。
        /// </summary>
        public static string _9D
        {
            get
            {
                return ResourceManager.GetString("9D", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x0E|顺手牵羊|0x01|0x0B|Ssqy1 的本地化字符串。
        /// </summary>
        public static string _9E
        {
            get
            {
                return ResourceManager.GetString("9E", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x0F|过河拆桥|0x01|0x0C|Ghcq1 的本地化字符串。
        /// </summary>
        public static string _9F
        {
            get
            {
                return ResourceManager.GetString("9F", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x0C|南蛮入侵|0x01|0x0D|Nmrq1 的本地化字符串。
        /// </summary>
        public static string A0
        {
            get
            {
                return ResourceManager.GetString("A0", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x0D|万箭齐发|0x02|0x01|Wjqf1 的本地化字符串。
        /// </summary>
        public static string A1
        {
            get
            {
                return ResourceManager.GetString("A1", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x01|闪|0x02|0x02|Shan1 的本地化字符串。
        /// </summary>
        public static string A2
        {
            get
            {
                return ResourceManager.GetString("A2", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x08|五谷丰登|0x02|0x03|Wgfd1 的本地化字符串。
        /// </summary>
        public static string A3
        {
            get
            {
                return ResourceManager.GetString("A3", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x08|五谷丰登|0x02|0x04|Wgfd1 的本地化字符串。
        /// </summary>
        public static string A4
        {
            get
            {
                return ResourceManager.GetString("A4", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x13|赤兔|0x02|0x05|Ct1 的本地化字符串。
        /// </summary>
        public static string A5
        {
            get
            {
                return ResourceManager.GetString("A5", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x05|乐不思蜀|0x02|0x06|Lbss1 的本地化字符串。
        /// </summary>
        public static string A6
        {
            get
            {
                return ResourceManager.GetString("A6", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x09|无中生有|0x02|0x07|Wzsy1 的本地化字符串。
        /// </summary>
        public static string A7
        {
            get
            {
                return ResourceManager.GetString("A7", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x09|无中生有|0x02|0x08|Wzsy1 的本地化字符串。
        /// </summary>
        public static string A8
        {
            get
            {
                return ResourceManager.GetString("A8", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x09|无中生有|0x02|0x09|Wzsy1 的本地化字符串。
        /// </summary>
        public static string A9
        {
            get
            {
                return ResourceManager.GetString("A9", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x01|杀|0x02|0x0A|Sha1 的本地化字符串。
        /// </summary>
        public static string AA
        {
            get
            {
                return ResourceManager.GetString("AA", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x09|无中生有|0x02|0x0B|Wzsy1 的本地化字符串。
        /// </summary>
        public static string AB
        {
            get
            {
                return ResourceManager.GetString("AB", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x0F|过河拆桥|0x02|0x0C|Ghcq1 的本地化字符串。
        /// </summary>
        public static string AC
        {
            get
            {
                return ResourceManager.GetString("AC", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x02|闪|0x02|0x0D|Shan1 的本地化字符串。
        /// </summary>
        public static string AD
        {
            get
            {
                return ResourceManager.GetString("AD", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x0A|决斗|0x03|0x01|Jd1 的本地化字符串。
        /// </summary>
        public static string AE
        {
            get
            {
                return ResourceManager.GetString("AE", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x01|杀|0x03|0x02|Sha1 的本地化字符串。
        /// </summary>
        public static string AF
        {
            get
            {
                return ResourceManager.GetString("AF", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x01|杀|0x03|0x03|Sha1 的本地化字符串。
        /// </summary>
        public static string B0
        {
            get
            {
                return ResourceManager.GetString("B0", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x01|杀|0x03|0x04|Sha1 的本地化字符串。
        /// </summary>
        public static string B1
        {
            get
            {
                return ResourceManager.GetString("B1", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x01|杀|0x03|0x05|Sha1 的本地化字符串。
        /// </summary>
        public static string B2
        {
            get
            {
                return ResourceManager.GetString("B2", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x01|杀|0x03|0x06|Sha1 的本地化字符串。
        /// </summary>
        public static string B3
        {
            get
            {
                return ResourceManager.GetString("B3", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x01|杀|0x03|0x07|Sha1 的本地化字符串。
        /// </summary>
        public static string B4
        {
            get
            {
                return ResourceManager.GetString("B4", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x01|杀|0x03|0x08|Sha1 的本地化字符串。
        /// </summary>
        public static string B5
        {
            get
            {
                return ResourceManager.GetString("B5", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x01|杀|0x03|0x09|Sha1 的本地化字符串。
        /// </summary>
        public static string B6
        {
            get
            {
                return ResourceManager.GetString("B6", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x01|杀|0x03|0x0A|Sha1 的本地化字符串。
        /// </summary>
        public static string B7
        {
            get
            {
                return ResourceManager.GetString("B7", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x01|杀|0x03|0x0B|Sha1 的本地化字符串。
        /// </summary>
        public static string B8
        {
            get
            {
                return ResourceManager.GetString("B8", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x06|无懈可击|0x03|0x0C|Wxkj1 的本地化字符串。
        /// </summary>
        public static string B9
        {
            get
            {
                return ResourceManager.GetString("B9", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x06|无懈可击|0x03|0x0D|Wxkj1 的本地化字符串。
        /// </summary>
        public static string BA
        {
            get
            {
                return ResourceManager.GetString("BA", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x0A|决斗|0x04|0x01|Jd1 的本地化字符串。
        /// </summary>
        public static string BB
        {
            get
            {
                return ResourceManager.GetString("BB", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x0A|闪|0x04|0x02|Shan1 的本地化字符串。
        /// </summary>
        public static string BC
        {
            get
            {
                return ResourceManager.GetString("BC", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x0E|顺手牵羊|0x04|0x03|Ssqy1 的本地化字符串。
        /// </summary>
        public static string BD
        {
            get
            {
                return ResourceManager.GetString("BD", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x0E|顺手牵羊|0x04|0x04|Ssqy1 的本地化字符串。
        /// </summary>
        public static string BE
        {
            get
            {
                return ResourceManager.GetString("BE", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x1A|贯石斧|0x04|0x05|Gsf1 的本地化字符串。
        /// </summary>
        public static string BF
        {
            get
            {
                return ResourceManager.GetString("BF", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x01|杀|0x04|0x06|Sha1 的本地化字符串。
        /// </summary>
        public static string C0
        {
            get
            {
                return ResourceManager.GetString("C0", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x01|杀|0x04|0x07|Sha1 的本地化字符串。
        /// </summary>
        public static string C1
        {
            get
            {
                return ResourceManager.GetString("C1", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x01|杀|0x04|0x08|Sha1 的本地化字符串。
        /// </summary>
        public static string C2
        {
            get
            {
                return ResourceManager.GetString("C2", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x01|杀|0x04|0x09|Sha1 的本地化字符串。
        /// </summary>
        public static string C3
        {
            get
            {
                return ResourceManager.GetString("C3", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x01|杀|0x04|0x0A|Sha1 的本地化字符串。
        /// </summary>
        public static string C4
        {
            get
            {
                return ResourceManager.GetString("C4", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x02|闪|0x04|0x0B|Shan1 的本地化字符串。
        /// </summary>
        public static string C5
        {
            get
            {
                return ResourceManager.GetString("C5", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x02|方天画戟|0x04|0x0C|Fthj1 的本地化字符串。
        /// </summary>
        public static string C6
        {
            get
            {
                return ResourceManager.GetString("C6", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x1D|紫骍|0x04|0x0D|Zs1 的本地化字符串。
        /// </summary>
        public static string C7
        {
            get
            {
                return ResourceManager.GetString("C7", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x17|寒冰剑|0x01|0x02|Hbj1 的本地化字符串。
        /// </summary>
        public static string C9
        {
            get
            {
                return ResourceManager.GetString("C9", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x04|闪电|0x02|0x0C|Sd1 的本地化字符串。
        /// </summary>
        public static string E0
        {
            get
            {
                return ResourceManager.GetString("E0", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 0x20|仁王盾|0x03|0x02|Rwd1 的本地化字符串。
        /// </summary>
        public static string E3
        {
            get
            {
                return ResourceManager.GetString("E3", resourceCulture);
            }
        }
    }
}
